export const COMPANY_QUESTION_BANK: Record<string, string[]> = {
  "Amazon": [
    "How would you design a highly scalable product catalog system like Amazon?",
    "Explain how Amazon ensures eventual consistency in distributed systems.",
    "How would you optimize delivery route planning?",
    "Describe how you would handle millions of concurrent orders.",
    "Which Amazon Leadership Principle do you relate to and why?",
  ],
  "Google": [
    "How does Google’s search ranking system work at a high level?",
    "Explain how distributed storage like Bigtable works.",
    "How would you reduce latency in a global system?",
    "Design a simplified Google Maps routing system.",
    "How does Google handle massive-scale data indexing?",
  ],
  "Microsoft": [
    "How does Azure ensure high availability?",
    "Explain how Microsoft Teams handles real-time communication.",
    "Design a cloud file storage system like OneDrive.",
    "What is multitenancy in cloud platforms?",
    "How would you implement enterprise authentication?",
  ],
  "Meta": [
    "How would you design a news feed ranking system?",
    "How does Meta scale real-time messaging?",
    "Explain graph databases in social networks.",
    "How would you detect fake accounts?",
    "What challenges arise in content moderation at scale?",
  ],
  "Apple": [
    "How does iOS manage memory efficiently?",
    "Explain secure enclave architecture.",
    "Design a battery optimization system.",
    "How does Apple ensure ecosystem integration?",
    "What is sandboxing in macOS?",
  ],
  "Netflix": [
    "How does Netflix recommend movies?",
    "Design a video streaming architecture.",
    "How does Netflix handle global CDN distribution?",
    "What is chaos engineering?",
    "How would you prevent streaming interruptions?",
  ],
  "Tesla": [
    "How does real-time sensor data processing work in autonomous driving?",
    "Explain battery management systems.",
    "What challenges exist in over-the-air updates?",
    "How would you design a self-driving perception system?",
    "What safety mechanisms are critical in automotive software?",
  ],
  "IBM": [
    "How does hybrid cloud architecture work?",
    "Explain enterprise AI deployment challenges.",
    "What is mainframe modernization?",
    "How does IBM ensure data governance?",
    "Explain Watson AI use cases.",
  ],
  "Oracle": [
    "How does Oracle ensure ACID compliance?",
    "Explain Oracle RAC architecture.",
    "How does database sharding work?",
    "What is query optimization?",
    "How do you handle high transaction systems?",
  ],
  "Intel": [
    "Explain CPU pipeline stages.",
    "How does branch prediction improve performance?",
    "What is cache coherence?",
    "Explain instruction-level parallelism.",
    "How would you optimize low-level system code?",
  ],
  "Adobe": [
    "How does Photoshop handle large image rendering?",
    "Explain cloud-based creative collaboration.",
    "What is vector vs raster processing?",
    "How would you design a document editing sync system?",
    "How does Adobe Creative Cloud manage subscriptions?",
  ],
  "Cisco": [
    "Explain router packet forwarding.",
    "What is BGP and why is it important?",
    "How does Cisco ensure network security?",
    "Design a scalable enterprise network.",
    "What is SD-WAN?",
  ],
  "Salesforce": [
    "How does Salesforce CRM manage multi-tenant data?",
    "Explain Apex triggers.",
    "How would you integrate third-party APIs?",
    "What are challenges in SaaS scalability?",
    "Explain role-based access control.",
  ],
  "Accenture": [
    "How do you gather client requirements?",
    "Explain digital transformation strategy.",
    "How do you manage stakeholder expectations?",
    "Describe risk mitigation in IT projects.",
    "How do you align tech with business goals?",
  ],
  "TCS": [
    "How do you manage large offshore teams?",
    "Explain Agile implementation.",
    "What is client SLA management?",
    "How do you ensure code quality in enterprise projects?",
    "Explain cloud migration strategy.",
  ],
  "Infosys": [
    "Explain digital transformation lifecycle.",
    "How do you optimize legacy systems?",
    "What is DevOps adoption strategy?",
    "Explain enterprise automation.",
    "How do you manage global clients?",
  ],
  "Wipro": [
    "How do you implement cybersecurity frameworks?",
    "Explain ITIL processes.",
    "What is cloud modernization?",
    "How do you manage distributed teams?",
    "Explain service delivery models.",
  ],
  "Capgemini": [
    "Explain enterprise architecture.",
    "How do you handle digital consulting?",
    "What is transformation roadmap?",
    "Explain system integration.",
    "Risk management in large projects?",
  ],
  "Cognizant": [
    "How do you implement DevOps pipelines?",
    "Explain digital engineering.",
    "How do you handle healthcare IT compliance?",
    "Explain automation testing strategy.",
    "How do you ensure SLA adherence?",
  ],
  "HCL Technologies": [
    "What is infrastructure management?",
    "Explain cloud-native architecture.",
    "How do you handle incident management?",
    "What is digital workplace solution?",
    "Explain service transition process.",
  ],
  "Flipkart": [
    "How would you design inventory forecasting?",
    "Explain cart consistency issues.",
    "How do you prevent flash sale crashes?",
    "Design a recommendation engine.",
    "What is supply chain optimization?",
  ],
  "Paytm": [
    "How does UPI transaction flow work?",
    "Explain fraud detection mechanisms.",
    "What is end-to-end encryption in payments?",
    "How do you ensure high availability?",
    "Explain KYC verification system.",
  ],
  "Zoho": [
    "How does Zoho maintain SaaS scalability?",
    "Explain multi-tenant database design.",
    "What is CRM workflow automation?",
    "How do you handle API integrations?",
    "Explain cloud security strategy.",
  ],
  "Swiggy": [
    "How does order allocation algorithm work?",
    "Explain real-time location tracking.",
    "How do you optimize delivery time?",
    "What is surge pricing logic?",
    "How would you scale during peak hours?",
  ],
  "Zomato": [
    "How would you build restaurant recommendation system?",
    "Explain rating fraud detection.",
    "How do you manage large restaurant data?",
    "What is hyperlocal logistics?",
    "How do you ensure uptime during traffic spikes?",
  ],
  "Goldman Sachs": [
    "How would you design a low-latency trading system?",
    "Explain risk management in high-frequency trading.",
    "How do distributed systems ensure transactional consistency in financial systems?",
    "What is Value at Risk (VaR) and how is it computed?",
    "How would you detect fraudulent financial transactions?",
  ],
  "JPMorgan Chase": [
    "How does real-time payment settlement work?",
    "Explain secure API design for banking systems.",
    "How would you design a credit scoring model?",
    "What is regulatory compliance in financial software?",
    "How do you handle high-volume transaction processing?",
  ],
  "Deloitte": [
    "How do you approach digital transformation for a legacy enterprise?",
    "Explain business process re-engineering.",
    "How do you measure ROI of technology implementation?",
    "Describe managing cross-functional stakeholders.",
    "What risks arise in ERP implementations?",
  ],
  "EY": [
    "How would you implement data analytics in audit?",
    "What are internal control systems?",
    "Explain risk-based auditing.",
    "How do you ensure data integrity in financial systems?",
    "How would you automate compliance reporting?",
  ],
  "KPMG": [
    "What is governance risk and compliance (GRC)?",
    "How does cybersecurity auditing work?",
    "Explain financial data reconciliation systems.",
    "How do you identify operational risks?",
    "How would you analyze large datasets for anomalies?",
  ],
  "Samsung": [
    "How does Android OS interact with hardware drivers?",
    "Explain memory optimization in mobile devices.",
    "How would you improve smartphone battery performance?",
    "What is embedded firmware testing?",
    "How do you debug hardware-software integration issues?",
  ],
  "Qualcomm": [
    "How does 5G NR architecture differ from 4G?",
    "Explain signal modulation techniques.",
    "What is RF power optimization?",
    "How does SoC architecture improve performance?",
    "Explain firmware debugging process.",
  ],
  "NVIDIA": [
    "How does GPU parallelism accelerate AI workloads?",
    "Explain CUDA thread hierarchy.",
    "What is tensor core optimization?",
    "How would you optimize memory bandwidth usage?",
    "Explain deep learning inference acceleration.",
  ],
  "AMD": [
    "What is cache hierarchy optimization?",
    "Explain multi-core synchronization challenges.",
    "How does SMT improve CPU performance?",
    "What is power-efficient processor design?",
    "How do you benchmark processor performance?",
  ],
  "ServiceNow": [
    "How does ITSM workflow automation function?",
    "Explain incident management lifecycle.",
    "How would you integrate third-party enterprise systems?",
    "What is CMDB architecture?",
    "How do you manage role-based access control?",
  ],
  "SAP": [
    "Explain SAP HANA in-memory processing.",
    "How does ERP integrate finance and supply chain?",
    "What is ABAP performance tuning?",
    "How would you handle large-scale data migration?",
    "What are challenges in global ERP rollout?",
  ],
  "Byju's": [
    "How would you personalize learning recommendations?",
    "Explain adaptive testing algorithms.",
    "How do you measure student engagement analytics?",
    "What challenges exist in scaling EdTech platforms?",
    "How would you reduce churn in subscription-based models?",
  ],
  "Ola Cabs": [
    "How does dynamic pricing (surge pricing) work?",
    "Design a driver-rider matching system.",
    "Explain GPS tracking accuracy improvements.",
    "How do you handle peak-hour demand scaling?",
    "What fraud prevention systems are needed?",
  ],
  "Uber": [
    "How does Uber’s dispatch algorithm work?",
    "Explain real-time geospatial indexing.",
    "How would you build ETA prediction models?",
    "What is microservices observability?",
    "How do you ensure reliability in distributed systems?",
  ],
  "Meesho": [
    "How would you design a reseller marketplace architecture?",
    "Explain recommendation systems for low-cost products.",
    "How do you manage logistics for tier-2 cities?",
    "What is seller fraud detection?",
    "How would you optimize conversion rates?",
  ],
  "Airbnb": [
    "How would you design a dynamic pricing system for hosts?",
    "Explain how Airbnb detects fake listings.",
    "How would you build a global search and filtering system?",
    "Design a secure payment escrow system.",
    "How do you handle trust and safety at scale?",
  ],
  "Stripe": [
    "How does Stripe handle secure payment tokenization?",
    "Explain idempotency in payment APIs.",
    "How would you design a recurring billing system?",
    "What challenges arise in cross-border payments?",
    "How do you prevent payment fraud in real time?",
  ],
  "Palantir Technologies": [
    "How would you design a large-scale data integration pipeline?",
    "Explain data lineage and audit tracking.",
    "How do you secure sensitive government datasets?",
    "What is ontology modeling in data systems?",
    "How would you visualize complex intelligence data?",
  ],
  "SpaceX": [
    "How does telemetry data processing work in rockets?",
    "Explain fault tolerance in mission-critical systems.",
    "How would you design real-time flight monitoring software?",
    "What redundancy mechanisms are used in aerospace systems?",
    "How do you ensure software reliability under extreme conditions?",
  ],
  "LinkedIn": [
    "How would you design a connection recommendation algorithm?",
    "Explain how LinkedIn handles graph database scaling.",
    "How would you rank job search results?",
    "What anti-spam mechanisms are needed?",
    "How do you design a real-time notification system?",
  ],
  "Dropbox": [
    "How does file synchronization across devices work?",
    "Explain conflict resolution in distributed file systems.",
    "How would you optimize large file uploads?",
    "What is deduplication in storage systems?",
    "How do you ensure data durability?",
  ],
  "Atlassian": [
    "How would you design a ticket management workflow?",
    "Explain issue prioritization algorithms.",
    "How do you scale collaboration tools for enterprises?",
    "What is plugin-based architecture?",
    "How do you ensure uptime for SaaS products?",
  ],
  "ByteDance": [
    "How does TikTok’s recommendation algorithm work?",
    "Explain large-scale video content moderation systems.",
    "How would you design a real-time engagement tracking system?",
    "What is distributed caching strategy?",
    "How do you handle billions of daily video uploads?",
  ],
  "OpenAI": [
    "How would you design a large language model inference API?",
    "Explain transformer architecture basics.",
    "What challenges arise in scaling AI model serving?",
    "How do you ensure AI system safety and alignment?",
    "How would you monitor hallucinations in AI outputs?",
  ],
  "Razorpay": [
    "How does UPI payment gateway integration work?",
    "Explain webhook handling in payment systems.",
    "How would you design subscription billing infrastructure?",
    "What fraud detection mechanisms are used in fintech?",
    "How do you handle high transaction spikes during sales?",
  ],
};

export const AVAILABLE_COMPANIES = Object.keys(COMPANY_QUESTION_BANK);
